-- MySQL Script generated by MySQL Workbench
-- 05/22/16 03:21:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parcial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parcial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parcial` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `parcial` ;

-- -----------------------------------------------------
-- Table `parcial`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS parcial.`usuarios` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NOMBRE` VARCHAR(255) NOT NULL COMMENT '',
  `PASSWORD` VARCHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_USUARIO`)  COMMENT '',
  UNIQUE INDEX `NOMBRE_UNIQUE` (`NOMBRE` ASC)  COMMENT '');

  INSERT INTO `usuarios` (`NOMBRE`, `PASSWORD`) VALUES
('JUAN','123');

-- -----------------------------------------------------
-- Table `parcial`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial`.`productos` (
  `ID_PRODUCTOS` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NOMBRE` VARCHAR(45) NULL COMMENT '',
  `CATEGORIA` VARCHAR(45) NULL COMMENT '',
  `MARCA` VARCHAR(45) NULL COMMENT '',
  `PRECIO` TINYINT(45) NULL COMMENT '',
  PRIMARY KEY (`ID_PRODUCTOS`)  COMMENT '')
ENGINE = InnoDB;
 INSERT INTO `productos` (`NOMBRE`, `CATEGORIA`,`MARCA`,`PRECIO`) VALUES
('iphone','celular','apple',700);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
